version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DEBUG=1
      - PYTHONPATH=/app
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000/api
      - VITE_GOOGLE_CLIENT_ID=760122344085-er6bjl852r1g0e4bnj3jok6pdt43vc8e.apps.googleusercontent.com
      - VITE_REDIRECT_URI=http://localhost:5173/auth/callback
    depends_on:
      - backend
    command: yarn dev --host